#!/bin/sh
exec 2>&1

export PATH=/usr/qk/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin:/opt:/opt/bin

printf "Start Udhcp runit service...\n"

UDHCP_CONF_FILE="/etc/network/udhcpd.conf"
NETWORK_FILE="/etc/network/interfaces"
HOSTAPD_TMP_FILE="/tmp/hostapd_tmp_data"
IP_ADDR="10.254.1.1"
IP_NETMASK="255.255.255.0s"

sv check hostapd >/dev/null || exit 1

wlan0_flag=0
while [ "$wlan0_flag" -eq 0 ]; do
	if ifconfig wlan0 2> /dev/null; then
		wlan0_flag=1
	else
		wlan0_flag=0
	fi
	[ "$wlan0_flag" -eq 0 ] && sleep 0.5
done

if [ -f ${NETWORK_FILE} ]; then
	sed '1,/iface wlan0 inet/ d' < "${NETWORK_FILE}" > "${HOSTAPD_TMP_FILE}"

	while read -r line; do
		str=$(printf "%b" "${line}\n" |  grep -w "address")
		if [ $? -eq 0 ]; then
			if [ "${str:0:1}" != "#" ]; then
				IP_ADDR=$(printf "%b" "${str}\n" | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
			fi
		fi

		str=$(printf "%b" "${line}\n" |  grep -w "netmask")
		if [ $? -eq 0 ]; then
			if [ "${str:0:1}" != "#" ]; then
				IP_NETMASK=$(printf "%b" "${str}\n" | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
			fi
		fi
	done < "${HOSTAPD_TMP_FILE}"
fi

rm -rf "${HOSTAPD_TMP_FILE}"
ifconfig wlan0 "${IP_ADDR}" netmask "${IP_NETMASK}"
touch /var/lib/misc/udhcpd.leases
exec udhcpd -f "${UDHCP_CONF_FILE}"
